"""CLI shell for the gyrokinetic distribution-function loader-workflow.

The implementation lives in :mod:`postgkyl.loaders.gk_distf`; ``pg.load.gk_distf``
(the script API) and this command are both thin wrappers over it.

Script example::

    import postgkyl as pg
    import matplotlib.pyplot as plt

    distf = pg.load.gk_distf(name="gk_lorentzian_mirror", species="ion", frame=0)
    distf.sel(z0=0.0).plot()
    plt.show()

    # A range of frames returns a DatasetGroup, exactly like pg.load.many:
    frames = pg.load.gk_distf(name="gk_lorentzian_mirror", species="ion", frame="0:10")
    frames.sel(z0=0.0).animate()
"""

import typer
from typing import Annotated, Optional

from postgkyl.loaders.gk_distf import (
    load_gk_distf,
    resolve_frames,
    _resolve_optional_file_option,
)
from postgkyl.utils import verb_print


# Generated by LLMs, commented and verified by MR 3/16/26
def gk_distf(
    ctx: typer.Context,
    name: Annotated[str, typer.Option("--name", "-n", help="Simulation name prefix (e.g. gk_lorentzian_mirror).")],
    species: Annotated[str, typer.Option("--species", "-s", help="Species name (e.g. ion or elc).")],
    frame: Annotated[str, typer.Option("--frame", "-f", help="Frame number, comma separated values, or range. Use ':' for all frames\n and 'start:stop[:step]' for ranges.")],
    suffix: Annotated[Optional[str], typer.Option("--suffix", help="Use <name>-<species>_<suffix>_<frame>.gkyl as the input distribution.")] = "",
    jf_file: Annotated[Optional[str], typer.Option("--jf-file", help="Jf filename override. If omitted, the default naming convention is used.")] = None,
    jacobvel_file: Annotated[Optional[str], typer.Option("--jacobvel-file", help="jacobvel filename override. If omitted, the default naming convention is used.")] = None,
    jacobtot_inv_file: Annotated[Optional[str], typer.Option("--jacobtot-inv-file", help="jacobtot_inv filename override. If omitted, the default naming convention is used.")] = None,
    interp: Annotated[Optional[int], typer.Option("--interp", "-i", help="Interpolation onto a general mesh of specified amount.")] = None,
    c2p_vel: Annotated[Optional[str], typer.Option("--c2p-vel", "-v", help="Convert velocity-space computational to physical coordinates, using mapping\nin (optionally) given file (default *_mapc2p_vel.gkyl).")] = None,
    mc2nu: Annotated[Optional[str], typer.Option("--mc2nu", "-m", help="Convert non-uniform computational to field-aligned coordinates using mapping \nin (optionally) given file (default: *_mc2nu_pos_deflated.gkyl).")] = None,
    mapc2p: Annotated[Optional[str], typer.Option("--mapc2p", "-p", help="Convert position-space computational to Cartesian (GKYL_GEOMETRY_MAPC2P) or \ncylindrical (GKYL_GEOMETRY_TOKAMAK, GKYL_GEOMETRY_MIRROR) coordinates, using \nmapping in (optionally) given file (default: *_mapc2p.gkyl)")] = None,
    block: Annotated[Optional[int], typer.Option("--block", "-b", help="Use block-specific files with _b<idx> prefix, e.g. -b 1 loads <name>_b1-*.gkyl.")] = None,
    tag: Annotated[Optional[str], typer.Option("--tag", "-t", help="Tag for output dataset.")] = "f",
):
  """Gyrokinetics: loads and interpolates distribution function from files containing the
  distribution (f) times one or multiple Jacobians (jf). Optionally, use mappings (in files)
  to convert the native coordinates of jf to physical velocity space coordinates or
  Cartesian/cyclindrical position space coordinates."""
  data = ctx.obj.data

  verb_print(ctx, "Building distribution function for " + name)

  frames = resolve_frames(frame, name=name, species=species,
      suffix=suffix, block_idx=block)
  verb_print(ctx, f"Loading frames: {frames}")

  use_c2p_vel, mapc2p_vel_file = _resolve_optional_file_option(c2p_vel)
  use_mc2nu, mc2nu_file = _resolve_optional_file_option(mc2nu)
  use_mapc2p, mapc2p_file = _resolve_optional_file_option(mapc2p)

  for f in frames:
    out = load_gk_distf(
      name=name, species=species, frame=f,
      tag=tag, suffix=suffix,
      use_c2p_vel=use_c2p_vel,
      use_mc2nu=use_mc2nu, use_mapc2p=use_mapc2p,
      block_idx=block,
      interp=interp,
      jf_file=jf_file,
      mapc2p_vel_file=mapc2p_vel_file,
      jacobvel_file=jacobvel_file,
      mc2nu_file=mc2nu_file,
      mapc2p_file=mapc2p_file,
      jacobtot_inv_file=jacobtot_inv_file,
    )
    data.add(out)
  # end

  if len(frames) > 1:
    data.set_unique_labels()
  # end
# end
