"""Generate the typed ``postgkyl.api`` module from the pgkyl click commands.

The pgkyl command line is the single source of truth: every command and option
already carries a name, type, default and help string. This module introspects
that metadata and emits a real ``api.py`` with one typed method per command, so
that editors/Pylance get full signature and docstring help with no runtime
tricks (a purely dynamic wrapper would not be statically visible).

Usage:
    python -m postgkyl.api._api_gen          # rewrite src/postgkyl/api/api.py
    python -m postgkyl.api._api_gen --check   # exit non-zero if api.py is stale

The ``test_api_in_sync`` test (or a build step) can call :func:`render` to keep
the committed ``api.py`` from drifting away from the commands.
"""

from __future__ import annotations

import keyword
import os
import sys

import click

from postgkyl.pgkyl import cli

# ``load`` is provided by hand on _Session (it needs to stash the file names),
# so it is not generated here.
_SKIP = {"load"}

_HEADER = '''"""Typed, scriptable pgkyl API.

GENERATED by ``postgkyl.api._api_gen`` from the pgkyl click commands. Do not edit
by hand; run ``python -m postgkyl.api._api_gen`` to regenerate after changing
commands.

    from postgkyl.api import PgkylSession
    pg = PgkylSession()
    pg.load("file.gkyl")
    pg.gk_rz()
    pg.plot()
"""

from typing import Literal

from postgkyl.pgkyl import cli
from postgkyl.api.scripting import _Session


def _cmd(name: str):
  return cli.commands[name]


class PgkylSession(_Session):
'''


def _annotation(param: click.Parameter) -> str:
  """Map a click parameter type to a Python type annotation string."""
  ctype = param.type
  name = getattr(ctype, "name", "text")
  if getattr(param, "is_flag", False) or name == "boolean":
    base = "bool"
  elif name == "integer":
    base = "int"
  elif name in ("float", "floatrange"):
    base = "float"
  elif name == "choice":
    base = "Literal[" + ", ".join(repr(c) for c in ctype.choices) + "]"
  else:
    base = "str"
  # Variadic arguments / multiple options collect into a tuple.
  if getattr(param, "multiple", False) or getattr(param, "nargs", 1) == -1:
    return f"tuple[{base}, ...]"
  return base


def _is_collection(param: click.Parameter) -> bool:
  return getattr(param, "multiple", False) or getattr(param, "nargs", 1) == -1


def _default_repr(param: click.Parameter) -> str:
  """Python source for a parameter default; ``None`` when click leaves it unset."""
  default = param.default
  # click >=8.2 uses a Sentinel for "no default was given".
  if default is None or repr(default).startswith("Sentinel"):
    return "False" if getattr(param, "is_flag", False) else "None"
  if _is_collection(param):
    return "()"
  return repr(default)


def _safe_name(name: str) -> str:
  return name + "_" if keyword.iskeyword(name) else name


def _signature_parts(command: click.Command):
  """Return (required_params, optional_params) split for a valid Python signature."""
  required, optional = [], []
  for param in command.params:
    if param.name == "help":
      continue
    # Required positional arguments (no default) must come first.
    if isinstance(param, click.Argument) and param.required and not _is_collection(param):
      required.append(param)
    else:
      optional.append(param)
  return required, optional


def _render_command(cli_name: str, command: click.Command) -> str:
  method = cli_name.replace("-", "_")
  required, optional = _signature_parts(command)

  params_src = []
  for param in required:
    params_src.append(f"{_safe_name(param.name)}: {_annotation(param)}")
  for param in optional:
    ann = _annotation(param)
    default = _default_repr(param)
    if default == "None" and not ann.startswith("tuple"):
      ann = f"{ann} | None"
    params_src.append(f"{_safe_name(param.name)}: {ann} = {default}")

  joined = ",\n      ".join(params_src)
  signature = f"  def {method}(self,\n      {joined}):" if params_src else f"  def {method}(self):"

  # Docstring: command help + per-parameter help.
  doc = (command.help or "").strip()
  lines = ['    """' + (doc if doc else method)]
  all_params = required + optional
  if all_params:
    lines.append("")
    lines.append("    Args:")
    for param in all_params:
      opts = ", ".join(param.opts) if param.opts else param.name
      phelp = (getattr(param, "help", None) or "").strip().replace("\n", " ")
      lines.append(f"      {param.name}: ({opts}) {phelp}".rstrip())
  lines.append('    """')
  docstring = "\n".join(lines)

  passes = ", ".join(
      f"{param.name}={_safe_name(param.name)}" for param in all_params)
  call = f'    return self._run(_cmd("{cli_name}"){", " + passes if passes else ""})'

  return f"{signature}\n{docstring}\n{call}\n"


def render() -> str:
  """Return the full source text of the generated ``api.py``."""
  blocks = []
  for cli_name in sorted(cli.commands):
    if cli_name in _SKIP:
      continue
    blocks.append(_render_command(cli_name, cli.commands[cli_name]))
  return _HEADER + "\n".join(blocks)


def _target_path() -> str:
  return os.path.join(os.path.dirname(__file__), "api.py")


def main(argv=None) -> int:
  argv = argv if argv is not None else sys.argv[1:]
  text = render()
  path = _target_path()
  if "--check" in argv:
    try:
      with open(path, "r") as fh:
        current = fh.read()
    except FileNotFoundError:
      current = None
    if current != text:
      print("postgkyl/api/api.py is stale; run 'python -m postgkyl.api._api_gen'.")
      return 1
    print("postgkyl/api/api.py is up to date.")
    return 0
  with open(path, "w") as fh:
    fh.write(text)
  print(f"Wrote {path}")
  return 0


if __name__ == "__main__":
  raise SystemExit(main())
