"""Script-callable loader for Gkeyll gyrokinetic distribution functions.

Reads the saved ``Jf`` (distribution times one or more Jacobians) together with
the velocity/configuration Jacobians, divides them out, and interpolates onto a
nodal grid, optionally applying velocity- and position-space coordinate
mappings. Both ``pg.load.gk_distf`` and the CLI ``gk-distf`` command are thin
wrappers over :func:`load_gk_distf` (with :func:`resolve_frames` expanding a
frame specification into concrete indices).

MR was heavily inspired by LLMs (copilot) in writing the original of this
module. Highly specific, iterated prompts were used; the error handling was
trimmed down to the assumptions we can actually make about the data, and
``load_gk_distf`` was condensed. Commented and verified by MR 3/16/26.
"""

from __future__ import annotations

import glob
from typing import TYPE_CHECKING

import numpy as np

if TYPE_CHECKING:
  from postgkyl.data import GData
# end


def _resolve_optional_file_option(option_value: str | None) -> tuple[bool, str | None]:
  """Interpret an optional-value CLI option as (enabled, override_file)."""
  if option_value is None:
    return False, None
  if option_value == "":
    return True, None
  return True, option_value
# end


def resolve_frames(
    frame: "int | str | list | tuple",
    *, name: str, species: str, suffix: str = "", block_idx: int | None = None,
) -> list:
  """Expand a frame specification into a concrete sorted list of frame indices.

  Shared by the CLI ``gk_distf`` command and ``pg.load.gk_distf`` so both
  front-ends accept the same forms:

    - an ``int`` (single frame) -> ``[frame]``;
    - a ``list``/``tuple`` of ints -> the same ints;
    - a string with a single number ("7") or comma-separated numbers
      ("0,2,4");
    - a ``'start:stop[:step]'`` / ``':'`` range. Range bounds default to the
      first/last frame discovered on disk for the given simulation/species.
  """
  if isinstance(frame, int):
    return [frame]
  # end
  if isinstance(frame, (list, tuple)):
    return [int(f) for f in frame]
  # end

  frame_spec = str(frame).strip()
  if "," in frame_spec:
    return [int(f.strip()) for f in frame_spec.split(",")]  # Explicit list of frames
  # end
  if ":" not in frame_spec:
    return [int(frame_spec)]  # A single frame
  # end

  # Range form: discover how many frames are available on disk.
  # Generated by LLMs
  prefix = f"{name}_b{block_idx}" if block_idx is not None else name
  frame_infix = f"{suffix}_" if suffix else ""
  stem = f"{prefix}-{species}_{frame_infix}"
  available = sorted({
    int(f.removeprefix(stem)[:-5])
    for f in glob.glob(f"{glob.escape(stem)}*.gkyl")
    if f.removeprefix(stem)[:-5].isdigit()
  })
  parts = frame_spec.split(":")
  lower = int(parts[0]) if parts[0] else available[0]
  upper = int(parts[1]) if parts[1] else available[-1] + 1
  step  = int(parts[2]) if len(parts) == 3 and parts[2] else 1
  return [f for f in available if lower <= f < upper and (f - lower) % step == 0]
# end


def load_gk_distf(
    name: str, species: str, frame: int,
    tag: str = "f", suffix: str = "", use_c2p_vel: bool = False,
    use_mc2nu: bool = False, use_mapc2p: bool = False, block_idx: int | None = None,
    interp: int | None = None,
    jf_file: str | None = None,
    mapc2p_vel_file: str | None = None,
    jacobvel_file: str | None = None,
    mc2nu_file: str | None = None,
    mapc2p_file: str | None = None,
    jacobtot_inv_file: str | None = None,
) -> "GData":
  """Build a real distribution function from saved JBf data."""
  # Mostly by LLMs, but heavily refactored and verified by MR 3/16/26
  from postgkyl import ops
  from postgkyl.data import GData, GInterpModal

  prefix = f"{name}_b{block_idx}" if block_idx is not None else name
  frame_infix = f"{suffix}_" if suffix else ""

  if jf_file is None:
    jf_file = f"{prefix}-{species}_{frame_infix}{frame}.gkyl"
  # end
  if mapc2p_vel_file is None:
    mapc2p_vel_file = f"{prefix}-{species}_mapc2p_vel.gkyl"
  # end
  if jacobvel_file is None:
    jacobvel_file = f"{prefix}-{species}_jacobvel.gkyl"
  # end
  if mc2nu_file is None:
    mc2nu_file = f"{prefix}-mc2nu_pos_deflated.gkyl"
  # end
  if mapc2p_file is None:
    mapc2p_file = f"{prefix}-mapc2p_deflated.gkyl"
  # end
  if jacobtot_inv_file is None:
    jacobtot_inv_file = f"{prefix}-jacobtot_inv.gkyl"
  # end

  jf_data           = GData(jf_file)
  jacobvel_data     = GData(jacobvel_file)
  jacobtot_inv_data = GData(jacobtot_inv_file)

  # Divide Jf by jacobvel to get f * J_x * B.
  fjxB_data = GData(ctx=jf_data.ctx) # Inside a GData object so we can interpolate
  fjxB_values = jf_data.get_values() / jacobvel_data.get_values()
  fjxB_data.push(jf_data.get_grid(), fjxB_values)

  # Interpolate f * J_x * B and jacobtot_inv to the same grid.
  out_grid, fjxB_values    = GInterpModal(fjxB_data, 1, "gkhyb", interp).interpolate()
  _, jacobtot_inv_values   = GInterpModal(jacobtot_inv_data, 1, "ms", interp).interpolate()
  fjxB_values              = np.squeeze(fjxB_values)
  jacobtot_inv_values      = np.squeeze(jacobtot_inv_values)

  # Reshape jacobtot_inv to have 1 component over velocity dimensions, then multiply.
  vdim = fjxB_values.ndim - jacobtot_inv_values.ndim
  jacobtot_inv_reshaped = jacobtot_inv_values.reshape(jacobtot_inv_values.shape + (1,) * vdim)
  f_values = fjxB_values * jacobtot_inv_reshaped
  # Add 1 dimension to represent 1 component
  f_values = f_values.reshape(f_values.shape + (1,))

  out = GData(tag=tag, ctx=jf_data.ctx)
  out.push(out_grid, f_values)

  # All coordinate maps run on the already-interpolated data via the shared map
  # verb. Velocity space (c2p_vel) deforms the trailing axes; configuration
  # space (mc2nu / mapc2p) deforms the leading ones. A combined map is just two
  # map applications, so the grid_type label records which were applied.
  grid_type = []
  if use_c2p_vel:
    ops.map(out, mapc2p_vel_file, space="vel", inplace=True)
    grid_type.append("c2p_vel")
  # end
  if use_mc2nu:
    ops.map(out, mc2nu_file, space="conf", interp=interp, inplace=True)
    grid_type.append("mc2nu")
  elif use_mapc2p:
    ops.map(out, mapc2p_file, space="conf", interp=interp, inplace=True)
    grid_type.append("mapc2p")
  # end
  if grid_type:
    out.ctx["grid_type"] = " + ".join(grid_type)
  # end
  return out
# end
