# MR was heavily inspired by LLMs (copilot) in writing this file. Highly specific and detailed prompts were used, with several iterations of refactors. Copilot inserted several unnecessary error checks because it didn't understand the assumptions we can make about the data. It was incredibly helpful in checking. I had to remove a lot of functions it used to make load_gk_distf more concise.

"""
# Script example of usage in python
import postgkyl as pg
import matplotlib.pyplot as plt

distf = pg.load.gk_distf(name="gk_lorentzian_mirror", species="ion", frame=0)
distf.sel(z0=0.0).plot()
plt.show()

# A range of frames returns a DatasetGroup, exactly like pg.load.many:
frames = pg.load.gk_distf(name="gk_lorentzian_mirror", species="ion", frame="0:10")
frames.sel(z0=0.0).animate()
"""
import glob

import numpy as np
import typer
from typing import Optional
from typing_extensions import Annotated

from postgkyl import ops
from postgkyl.data import GData, GInterpModal
from postgkyl.utils import verb_print


def _resolve_optional_file_option(option_value: str | None) -> tuple[bool, str | None]:
  """Interpret an optional-value CLI option as (enabled, override_file)."""
  if option_value is None:
    return False, None
  if option_value == "":
    return True, None
  return True, option_value
# end

def resolve_frames(
    frame: "int | str | list | tuple",
    *, name: str, species: str, suffix: str = "", block_idx: int | None = None,
) -> list:
  """Expand a frame specification into a concrete sorted list of frame indices.

  Shared by the CLI ``gk_distf`` command and ``pg.load.gk_distf`` so both
  front-ends accept the same forms:

    - an ``int`` (single frame) -> ``[frame]``;
    - a ``list``/``tuple`` of ints -> the same ints;
    - a string with a single number ("7") or comma-separated numbers
      ("0,2,4");
    - a ``'start:stop[:step]'`` / ``':'`` range. Range bounds default to the
      first/last frame discovered on disk for the given simulation/species.
  """
  if isinstance(frame, int):
    return [frame]
  # end
  if isinstance(frame, (list, tuple)):
    return [int(f) for f in frame]
  # end

  frame_spec = str(frame).strip()
  if "," in frame_spec:
    return [int(f.strip()) for f in frame_spec.split(",")]  # Explicit list of frames
  # end
  if ":" not in frame_spec:
    return [int(frame_spec)]  # A single frame
  # end

  # Range form: discover how many frames are available on disk.
  # Generated by LLMs
  prefix = f"{name}_b{block_idx}" if block_idx is not None else name
  frame_infix = f"{suffix}_" if suffix else ""
  stem = f"{prefix}-{species}_{frame_infix}"
  available = sorted({
    int(f.removeprefix(stem)[:-5])
    for f in glob.glob(f"{glob.escape(stem)}*.gkyl")
    if f.removeprefix(stem)[:-5].isdigit()
  })
  parts = frame_spec.split(":")
  lower = int(parts[0]) if parts[0] else available[0]
  upper = int(parts[1]) if parts[1] else available[-1] + 1
  step  = int(parts[2]) if len(parts) == 3 and parts[2] else 1
  return [f for f in available if lower <= f < upper and (f - lower) % step == 0]
# end


# Public API
def load_gk_distf(
    name: str, species: str, frame: int,
    tag: str = "f", suffix: str = "", use_c2p_vel: bool = False,
    use_mc2nu: bool = False, use_mapc2p: bool = False, block_idx: int | None = None,
    interp: int | None = None,
    jf_file: str | None = None,
    mapc2p_vel_file: str | None = None,
    jacobvel_file: str | None = None,
    mc2nu_file: str | None = None,
    mapc2p_file: str | None = None,
    jacobtot_inv_file: str | None = None,
) -> GData:
  """Build a real distribution function from saved JBf data."""
  # Mostly by LLMs, but heavily refactored and verified by MR 3/16/26
  prefix = f"{name}_b{block_idx}" if block_idx is not None else name
  frame_infix = f"{suffix}_" if suffix else ""

  if jf_file is None:
    jf_file = f"{prefix}-{species}_{frame_infix}{frame}.gkyl"
  # end
  if mapc2p_vel_file is None:
    mapc2p_vel_file = f"{prefix}-{species}_mapc2p_vel.gkyl"
  # end
  if jacobvel_file is None:
    jacobvel_file = f"{prefix}-{species}_jacobvel.gkyl"
  # end
  if mc2nu_file is None:
    mc2nu_file = f"{prefix}-mc2nu_pos_deflated.gkyl"
  # end
  if mapc2p_file is None:
    mapc2p_file = f"{prefix}-mapc2p_deflated.gkyl"
  # end
  if jacobtot_inv_file is None:
    jacobtot_inv_file = f"{prefix}-jacobtot_inv.gkyl"
  # end

  jf_data           = GData(jf_file, mapc2p_vel_name=mapc2p_vel_file if use_c2p_vel else None)
  jacobvel_data     = GData(jacobvel_file)
  jacobtot_inv_data = GData(jacobtot_inv_file)

  # Divide Jf by jacobvel to get f * J_x * B.
  fjxB_data = GData(ctx=jf_data.ctx) # Inside a GData object so we can interpolate
  fjxB_values = jf_data.get_values() / jacobvel_data.get_values()
  fjxB_data.push(jf_data.get_grid(), fjxB_values)

  # Interpolate f * J_x * B and jacobtot_inv to the same grid.
  out_grid, fjxB_values    = GInterpModal(fjxB_data, 1, "gkhyb", interp).interpolate()
  _, jacobtot_inv_values   = GInterpModal(jacobtot_inv_data, 1, "ms", interp).interpolate()
  fjxB_values              = np.squeeze(fjxB_values)
  jacobtot_inv_values      = np.squeeze(jacobtot_inv_values)

  # Reshape jacobtot_inv to have 1 component over velocity dimensions, then multiply.
  vdim = fjxB_values.ndim - jacobtot_inv_values.ndim
  jacobtot_inv_reshaped = jacobtot_inv_values.reshape(jacobtot_inv_values.shape + (1,) * vdim)
  f_values = fjxB_values * jacobtot_inv_reshaped
  # Add 1 dimension to represent 1 component
  f_values = f_values.reshape(f_values.shape + (1,))

  out = GData(tag=tag, ctx=jf_data.ctx)
  out.push(out_grid, f_values)

  # Deform the (uniform) configuration-space grid onto the physical coordinates
  # via the shared map verb. Velocity-space mapping (c2p_vel) is applied at
  # load time by the reader above; a combined map is two map applications.
  if use_mc2nu:
    ops.map(out, mc2nu_file, space="conf", interp=interp, inplace=True)
    out.ctx["grid_type"] = "c2p_vel + mc2nu" if use_c2p_vel else "mc2nu"
  elif use_mapc2p:
    ops.map(out, mapc2p_file, space="conf", interp=interp, inplace=True)
    out.ctx["grid_type"] = "c2p_vel + mapc2p" if use_c2p_vel else "mapc2p"
  # end
  return out
# end

# Generated by LLMs, commented and verified by MR 3/16/26
def gk_distf(
    ctx: typer.Context,
    name: Annotated[str, typer.Option("--name", "-n", help="Simulation name prefix (e.g. gk_lorentzian_mirror).")],
    species: Annotated[str, typer.Option("--species", "-s", help="Species name (e.g. ion or elc).")],
    frame: Annotated[str, typer.Option("--frame", "-f", help="Frame number, comma separated values, or range. Use ':' for all frames\n and 'start:stop[:step]' for ranges.")],
    suffix: Annotated[Optional[str], typer.Option("--suffix", help="Use <name>-<species>_<suffix>_<frame>.gkyl as the input distribution.")] = "",
    jf_file: Annotated[Optional[str], typer.Option("--jf-file", help="Jf filename override. If omitted, the default naming convention is used.")] = None,
    jacobvel_file: Annotated[Optional[str], typer.Option("--jacobvel-file", help="jacobvel filename override. If omitted, the default naming convention is used.")] = None,
    jacobtot_inv_file: Annotated[Optional[str], typer.Option("--jacobtot-inv-file", help="jacobtot_inv filename override. If omitted, the default naming convention is used.")] = None,
    interp: Annotated[Optional[int], typer.Option("--interp", "-i", help="Interpolation onto a general mesh of specified amount.")] = None,
    c2p_vel: Annotated[Optional[str], typer.Option("--c2p-vel", "-v", help="Convert velocity-space computational to physical coordinates, using mapping\nin (optionally) given file (default *_mapc2p_vel.gkyl).")] = None,
    mc2nu: Annotated[Optional[str], typer.Option("--mc2nu", "-m", help="Convert non-uniform computational to field-aligned coordinates using mapping \nin (optionally) given file (default: *_mc2nu_pos_deflated.gkyl).")] = None,
    mapc2p: Annotated[Optional[str], typer.Option("--mapc2p", "-p", help="Convert position-space computational to Cartesian (GKYL_GEOMETRY_MAPC2P) or \ncylindrical (GKYL_GEOMETRY_TOKAMAK, GKYL_GEOMETRY_MIRROR) coordinates, using \nmapping in (optionally) given file (default: *_mapc2p.gkyl)")] = None,
    block: Annotated[Optional[int], typer.Option("--block", "-b", help="Use block-specific files with _b<idx> prefix, e.g. -b 1 loads <name>_b1-*.gkyl.")] = None,
    tag: Annotated[Optional[str], typer.Option("--tag", "-t", help="Tag for output dataset.")] = "f",
):
  """Gyrokinetics: loads and interpolates distribution function from files containing the
  distribution (f) times one or multiple Jacobians (jf). Optionally, use mappings (in files)
  to convert the native coordinates of jf to physical velocity space coordinates or
  Cartesian/cyclindrical position space coordinates."""
  kwargs = {k: v for k, v in locals().items() if k != "ctx"}
  data = ctx.obj["data"]

  verb_print(ctx, "Building distribution function for " + kwargs["name"])

  frames = resolve_frames(kwargs["frame"], name=kwargs["name"], species=kwargs["species"],
      suffix=kwargs["suffix"], block_idx=kwargs["block"])
  verb_print(ctx, f"Loading frames: {frames}")

  use_c2p_vel, mapc2p_vel_file = _resolve_optional_file_option(kwargs["c2p_vel"])
  use_mc2nu, mc2nu_file = _resolve_optional_file_option(kwargs["mc2nu"])
  use_mapc2p, mapc2p_file = _resolve_optional_file_option(kwargs["mapc2p"])

  for frame in frames:
    out = load_gk_distf(
      name=kwargs["name"], species=kwargs["species"], frame=frame,
      tag=kwargs["tag"], suffix=kwargs["suffix"],
      use_c2p_vel=use_c2p_vel,
      use_mc2nu=use_mc2nu, use_mapc2p=use_mapc2p,
      block_idx=kwargs["block"],
      interp=kwargs["interp"],
      jf_file=kwargs["jf_file"],
      mapc2p_vel_file=mapc2p_vel_file,
      jacobvel_file=kwargs["jacobvel_file"],
      mc2nu_file=mc2nu_file,
      mapc2p_file=mapc2p_file,
      jacobtot_inv_file=kwargs["jacobtot_inv_file"],
    )
    data.add(out)
  # end

  if len(frames) > 1:
    data.set_unique_labels()
  # end
# end
